In [1]:
# Import Libraries
import numpy as np
import pandas as pd
import glob
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

### General Dataset

In [4]:
df = pd.read_csv(r'/content/drive/My Drive/Predictive Analysis of Crowdfunding Platforms/7.General Dataset (Final)/General Dataset Cleaned Final 1.csv')
df.head()

                                                name  ... state
0                   Ardmore Junction: A Feature Film  ...     1
1        Support producing 3 Peace Day events in NYC  ...     1
2  Mojobot - World's first tangible coding robot ...  ...     1
3  The World's Best Passport Case for Two | futar...  ...     1
4  The Little Girl, The Ocean, and The Moon: A Ch...  ...     1

[5 rows x 17 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 153877 entries, 0 to 153876
Data columns (total 17 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   name                    153877 non-null  object
 1   description             153877 non-null  object
 2   country                 153877 non-null  int64
 3   currency                153877 non-null  int64
 4   main_category           153877 non-null  int64
 5   sub_category            153877 non-null  int64
 6   time_before_launch      153877 non-null  int64
 7   state_change_time       153877 non-null  int64
 8   funding_time            153877 non-null  int64
 9   goal_amount             153877 non-null  float64
 10  goal_amount_usd         153877 non-null  int64
 11  pledged_amount          153877 non-null  float64
 12  pledged_amount_usd      153877 non-null  int64
 13  no_of_backers           153877 non-null  int64
 14  description_score       153877 non-null  float64
 15  description_prediction  153877 non-null  int64
 16  state                   153877 non-null  int64
dtypes: float64(3), int64(12), object(2)
memory usage: 20.0+ MB

In [ ]:
df.describe()

             country       currency  ...  description_prediction          state
count  153877.000000  153877.000000  ...           153877.000000  153877.000000
mean        2.148729       1.756266  ...                0.631192       0.590628
std         3.021785       1.767894  ...                0.482483       0.491720
min         1.000000       1.000000  ...                0.000000       0.000000
25%         1.000000       1.000000  ...                0.000000       0.000000
50%         1.000000       1.000000  ...                1.000000       1.000000
75%         2.000000       2.000000  ...                1.000000       1.000000
max        22.000000      14.000000  ...                1.000000       1.000000

[8 rows x 15 columns]

### Rewards Dataset

In [ ]:
df = pd.read_csv(r'/content/drive/My Drive/Predictive Analysis of Crowdfunding Platforms/11.Rewards Dataset (Final)/Rewards Dataset Cleaned Final.csv')
df.head()

   main_category  sub_category  country  ...  max_reward  mean_reward  median_reward
0              1             1       10  ...        2500          632            250
1              7             2       10  ...          50           18             10
2              1             3       10  ...        5000          557             85
3             10             4       10  ...         250           98             75
4              1             1       10  ...        1000          276            100

[5 rows x 16 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40479 entries, 0 to 40478
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   main_category  40479 non-null  int64
 1   sub_category   40479 non-null  int64
 2   country        40479 non-null  int64
 3   status         40479 non-null  int64
 4   goal           40479 non-null  int64
 5   pledged        40479 non-null  int64
 6   backers        40479 non-null  int64
 7   levels         40479 non-null  int64
 8   reward_levels  40479 non-null  object
 9   duration       40479 non-null  int64
 10  min_reward     40479 non-null  int64
 11  max_reward     40479 non-null  int64
 12  mean_reward    40479 non-null  int64
 13  median_reward  40479 non-null  int64
dtypes: int64(13), object(1)
memory usage: 4.3+ MB

In [ ]:
df.describe()

       main_category  sub_category  ...   mean_reward  median_reward
count   40479.000000  40479.000000  ...  40479.000000   40479.000000
mean        3.641271     16.831962  ...    392.690778     104.626646
std         3.149447     13.063287  ...    512.562311     185.030354
min         1.000000      1.000000  ...      1.000000       1.000000
25%         1.000000      5.000000  ...     83.000000      38.000000
50%         2.000000     12.000000  ...    211.000000      75.000000
75%         5.000000     27.000000  ...    466.000000     100.000000
max        13.000000     49.000000  ...  10000.000000   10000.000000

[8 rows x 13 columns]

### Social Media Dataset

In [5]:
df = pd.read_csv(r'/content/drive/My Drive/Predictive Analysis of Crowdfunding Platforms/9.Content Dataset (Final)/Content Dataset Cleaned Final.csv')
df.head()

   Status  Currency  ...  Risks and Challenges Words  FAQ
0       0         1  ...                         153    0
1       0         1  ...                          98    0
2       0         1  ...                          66    2
3       0         1  ...                         169    0
4       0         1  ...                         216    0

[5 rows x 21 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18065 entries, 0 to 18064
Data columns (total 21 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Status                      18065 non-null  int64
 1   Currency                    18065 non-null  int64
 2   Main Category               18065 non-null  int64
 3   Sub Category                18065 non-null  int64
 4   Rewards                     18065 non-null  int64
 5   Goal                        18065 non-null  int64
 6   Pledged                     18065 non-null  int64
 7   Backers                     18065 non-null  int64
 8   Duration                    18065 non-null  int64
 9   Facebook Connected          18065 non-null  int64
 10  Facebook Friends            18065 non-null  int64
 11  Facebook Shares             18065 non-null  int64
 12  Has Video                   18065 non-null  int64
 13  Has Website                 18065 non-null  int64
 14  Projects Created            18065 non-null  int64
 15  Projects Backed             18065 non-null  int64
 16  Videos                      18065 non-null  int64
 17  Images                      18065 non-null  int64
 18  Description Words           18065 non-null  int64
 19  Risks and Challenges Words  18065 non-null  int64
 20  FAQ                         18065 non-null  int64
dtypes: int64(21)
memory usage: 2.9 MB

In [ ]:
df.describe()

             Status      Currency  ...  Risks and Challenges Words           FAQ
count  18065.000000  18065.000000  ...                18065.000000  18065.000000
mean       0.497924      1.337448  ...                  129.775588      0.677830
std        0.500010      0.773829  ...                   97.240961      2.046338
min        0.000000      1.000000  ...                    0.000000      0.000000
25%        0.000000      1.000000  ...                   68.000000      0.000000
50%        0.000000      1.000000  ...                  105.000000      0.000000
75%        1.000000      1.000000  ...                  163.000000      0.000000
max        1.000000      6.000000  ...                 1888.000000     47.000000

[8 rows x 21 columns]